include:
  files:
    - "**/*"

exclude:
  files:
    # exclude any test related file or folder
    - "test*"
    - "config/SNOMED_codes/diagnosis_codes_GB.json"
    
  keys:
    - .*(public|project).*
    # exclude api keys
    - .*api_key.*
    
  values:
    - ^(true|false|yes|no|1|0)$
    - .*_(user|password|token|key|placeholder|name)$
    - ^aws_(access_key_id|secret_access_key|session_token)$
    - ^arn:aws:.*
