# This is a basic workflow to help you get started with Actions

name: Secrets scanner

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        name: Check out code
      
      - name: install whispers
        run: pip3 install whispers 
      
      - name: run whispers
        run: whispers --config secretsconfig.yml ./
